[build]
  publish = "public"
  command = "hugo --gc --minify"

[context.deploy-preview]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.production.environment]
  HUGO_VERSION = "0.132.1"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.132.1"
